"""empty message

Revision ID: 15df65e2a446
Revises: 
Create Date: 2026-05-13 12:31:04.212128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15df65e2a446'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    #STANDART
    op.add_column('participants',
                  sa.Column('role', sa.String(), nullable=False, server_default='voter'))
    op.alter_column("participants", "role", server_default=None)

    #ENUM ADD
    proposal_status_enum = sa.Enum(
        'DRAFT',
        'VOTING',
        'APPROVED',
        'REJECTED',
        name='proposalstatus'
    )
    proposal_status_enum.create(op.get_bind(), checkfirst=True)
    op.alter_column('proposals', 'status',
                postgresql_using="status::proposalstatus",
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('DRAFT', 'VOTING', 'APPROVED', 'REJECTED', name='proposalstatus'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    #ENUM DELETE
    op.alter_column('proposals', 'status',
               existing_type=sa.Enum('DRAFT', 'VOTING', 'APPROVED', 'REJECTED', name='proposalstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    proposal_status_enum = sa.Enum(
        'DRAFT',
        'VOTING',
        'APPROVED',
        'REJECTED',
        name='proposalstatus'
    )

    proposal_status_enum.drop(op.get_bind(), checkfirst=True)

    op.drop_column('participants', 'role')
    # ### end Alembic commands ###
