"""add updated_at to products

Revision ID: 581ba369bf20
Revises: 656734dd6137
Create Date: 2026-03-17 14:33:17.346999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '581ba369bf20'
down_revision: Union[str, Sequence[str], None] = '656734dd6137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('updated_at', sa.DateTime(), nullable=False), schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'updated_at', schema='core')
    # ### end Alembic commands ###
