print("200 — OK: Request succeeded")
print("201 — Created: Successfully created")
print("204 — No content: Request succeeded but no body returned")
print("301 — Moved permanently: Resource moved to another URL")
print("400 — Bad request: Client sent invalid data")
print("401 — Unauthorized: Authentication required of failed")
print("403 — Forbidden: Client authenticated but not allowed")
print("404 — Not found: Resource does not exist")
print("500 — Internal server error: Server crashed")
print("503 — Service unavailable: Server temporarily unavailable")